const $=i=>document.getElementById(i),C={quotation:['Quotation','QT','Expires On'],proforma:['Proforma Invoice','PI','Valid Until'],invoice:['Invoice','INV','Due Date']},K='quo_current',KN='quo_numbers';let s;
const M=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}),F=d=>d?new Date(d+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}).replaceAll(' ','-'):'',E=v=>{let x=document.createElement('div');x.textContent=v??'';return x.innerHTML};
function P(a,b){if(!a&&!b)return'';if(!b)return F(a);let x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00'),ma=x.toLocaleDateString('en-GB',{month:'long'}),mb=y.toLocaleDateString('en-GB',{month:'long'}),ya=x.getFullYear(),yb=y.getFullYear();return ma==mb&&ya==yb?`${x.getDate()}-${y.getDate()} ${ma} ${ya}`:`${F(a)} - ${F(b)}`}
function N(t){let n=JSON.parse(localStorage.getItem(KN)||'{}');n[t]=(n[t]||0)+1;localStorage.setItem(KN,JSON.stringify(n));return C[t][1]+'/'+String(n[t]).padStart(3,'0')}
function menu(){return`Day 1
Morning Coffee 04:30-05:30: Hot Milo
Breakfast 07:15-08:15: Bread, Butter, Peanut Butter, Jam, Roshi, Baked Beans, Kulhimas, Omelette, Banana, Tea
Lunch 12:00-14:00: White Rice, Roshi, Fish Curry, Dhaal Curry, Salad, Papadum, Custard, Juice
Tea Break 15:30-16:30: Sandwich, Tuna, Bis Keemiya, Gulha, Boakibaa, Butter Cake, Roast Paan, Tea
Dinner 20:00-21:00: White Rice, Spaghetti, Devilled Chicken, Fish Curry, Salad, Papadum, Custard, Juice
Red Coffee 22:30-23:00: Hot Milo

Day 2
Morning Coffee 04:30-05:30: Hot Milo
Breakfast 07:15-08:15: Bread, Butter, Peanut Butter, Jam, Roshi, Mashuni, Boiled Eggs, Banana, Tea
Lunch 12:00-14:00: White Rice, Fried Noodles, Devilled Fish, Chicken Curry, Mixed Salad, Papadum, Fruits, Juice
Red Coffee 22:30-23:00: Hot Milo
Tea Break: Not Required
Dinner: Not Required`}
function fresh(t='quotation'){s={type:t,number:N(t),date:'',due:'',status:'Draft',currency:'MVR',customer:'Muhyiddin School',phone:'9997870',address:'',useService:true,serviceType:'Catering - Buffet',serviceFrom:'2026-08-22',serviceTo:'2026-08-23',servicePax:200,serviceLabel:'Buffet Period',items:[{description:'2-Day Meal Package - Per Pax',qty:200,unit:'Pax',price:600}],gstMode:'none',gstRate:8,discount:0,showGst:false,includeMenu:true,menuTitle:'MESS MENU',menu:menu(),useAdvance:false,advance:50,advanceDate:'',bank:'Bank of Maldives (BML)',account:'',slipVia:'Viber',slipNo:'',extra:''};bind()}
function bind(){Object.keys(s).forEach(k=>{if($(k)&&!Array.isArray(s[k]))$(k).value=s[k]??''});['useService','showGst','includeMenu','useAdvance'].forEach(k=>$(k).checked=!!s[k]);draw();render()}
function read(){['date','due','status','currency','customer','phone','address','serviceType','serviceFrom','serviceTo','serviceLabel','gstMode','menuTitle','menu','bank','account','slipVia','slipNo','extra'].forEach(k=>s[k]=$(k).value);['servicePax','gstRate','discount','advance'].forEach(k=>s[k]=Number($(k).value||0));['useService','showGst','includeMenu','useAdvance'].forEach(k=>s[k]=$(k).checked);s.advanceDate=$('advanceDate').value}
function draw(){$('items').innerHTML=s.items.map((i,n)=>`<div class="item" data-i="${n}"><div><label>Description</label><input data-k="description" value="${E(i.description)}"></div><div><label>Qty</label><input data-k="qty" type="number" value="${i.qty}"></div><div><label>Unit</label><input data-k="unit" value="${E(i.unit)}"></div><div><label>Price</label><input data-k="price" type="number" value="${i.price}"></div><button class="remove" onclick="removeItem(${n})">x</button></div>`).join('')}
function calc(){let r=s.items.reduce((a,i)=>a+i.qty*i.price,0),d=Math.min(s.discount,r),b=r-d,g=0,n=b;if(s.gstMode=='exclusive')g=b*s.gstRate/100;if(s.gstMode=='inclusive'){g=b-b/(1+s.gstRate/100);n=b-g}return{r,d,g,n,t:s.gstMode=='exclusive'?b+g:b}}
function addDays(d,n){let x=new Date(d+'T00:00:00');x.setDate(x.getDate()+n);return x}
function renderMenu(){let on=s.includeMenu&&s.menu.trim();$('menuPage').classList.toggle('hidden',!on);if(!on)return;$('pMenuTitle').textContent=s.menuTitle;$('menuDocRef').textContent=s.number;$('menuSub').textContent=s.customer;$('menuBadge').textContent=s.servicePax+' Pax';$('menuService').classList.toggle('hidden',!s.useService);$('menuServiceType').textContent=s.serviceType;$('menuServicePeriod').textContent=P(s.serviceFrom,s.serviceTo);let ds=[],cur;for(let l of s.menu.split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){if(/^Day\s+\d+/i.test(l)){cur=[];ds.push(cur);continue}if(!cur)continue;let m=l.match(/^(.+?)(?:\s+(\d\d:\d\d-\d\d:\d\d))?:\s*(.+)$/);if(m)cur.push(m)}$('fallbackMenu').classList.toggle('hidden',!!ds.length);$('menuGrid').classList.toggle('hidden',!ds.length);if(!ds.length){$('fallbackMenu').textContent=s.menu;return}$('menuGrid').innerHTML=ds.map((d,i)=>{let dt=s.serviceFrom?addDays(s.serviceFrom,i):null,h=dt?`DAY ${i+1} - ${dt.toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}).toUpperCase()}`:`DAY ${i+1}`;return`<section class="day-card"><div class="day-head"><div class="day-kicker">Service Schedule</div><div class="day-title">${h}</div></div>${d.map(m=>`<div class="meal"><div><div class="meal-name">${E(m[1])}</div>${m[2]?`<div class="meal-time">${m[2]}</div>`:''}</div><div class="meal-items ${/not required/i.test(m[3])?'not-required':''}">${E(m[3])}</div></div>`).join('')}</section>`}).join('')}
function render(){read();let c=calc(),t=C[s.type],sv=s.useService;$('serviceFields').classList.toggle('disabled',!sv);$('advanceFields').classList.toggle('disabled',!s.useAdvance);$('dueLabel').textContent=t[2]+' - Optional';$('chip').textContent=s.number;$('eSub').textContent=M(s.gstMode=='inclusive'?c.n:c.r);$('eGst').textContent=M(c.g);$('eTotal').textContent=M(c.t);$('pTitle').textContent=sv?'Catering '+t[0]:t[0];$('pStatus').textContent=s.status;$('pNumber').textContent=$('pNumber2').textContent=s.number;$('pCustomer').textContent=s.customer;$('pPhone').textContent=s.phone;$('pAddress').textContent=s.address;$('pDate').textContent=s.date?F(s.date):'Not set';$('pDueLabel').textContent=s.due?t[2]:'';$('pDue').textContent=s.due?F(s.due):'';$('pServiceBanner').classList.toggle('hidden',!sv);if(sv){$('pServiceType').textContent=s.serviceType;$('pServiceLabel').textContent=s.serviceLabel;$('pServicePeriod').textContent=P(s.serviceFrom,s.serviceTo);$('pServicePax').textContent=s.servicePax}$('pItems').innerHTML=s.items.map((i,n)=>`<tr><td>${n+1}</td><td class="desc">${E(i.description)}</td><td class="qty">${i.qty}</td><td>${E(i.unit)}</td><td class="num">${M(i.price)}</td><td class="num">${M(i.qty*i.price)}</td></tr>`).join('');$('pSub').textContent=M(s.gstMode=='inclusive'?c.n:c.r);$('pDisc').textContent=M(c.d);$('pDiscRow').classList.toggle('hidden',!c.d);$('pGstLabel').textContent='GST @ '+s.gstRate+'%';$('pGst').textContent=M(c.g);$('pGstRow').classList.toggle('hidden',!(s.showGst||c.g));$('pTotalLabel').textContent='Total ('+s.currency+')';$('pTotal').textContent=M(c.t);$('summaryNote').textContent=(sv?`${s.serviceType}: ${P(s.serviceFrom,s.serviceTo)}. `:'')+(s.includeMenu?'Meal details are on the attached menu page.':'');let a=c.t*s.advance/100,b=c.t-a;$('pAdvanceBox').classList.toggle('hidden',!s.useAdvance);if(s.useAdvance){$('pAdvanceValue').textContent=s.currency+' '+M(a);$('pAdvanceDue').textContent=s.advanceDate?'Due on or before '+F(s.advanceDate):'Advance due date to be confirmed';$('pBalanceValue').textContent=s.currency+' '+M(b)}let q=[];if(sv)q.push(`${s.serviceType}: ${P(s.serviceFrom,s.serviceTo)} - ${s.servicePax} Pax.`);if(s.useAdvance)q.push(`${s.advance}% advance payment of ${s.currency} ${M(a)}${s.advanceDate?' is required on or before '+F(s.advanceDate):' is required to confirm the booking'}. Remaining balance: ${s.currency} ${M(b)}.`);if(s.bank||s.account)q.push(`Bank Transfer: ${s.bank}${s.account?' - Account No.: '+s.account:''}`);if(s.slipVia||s.slipNo)q.push(`After payment, please send the payment slip${s.slipVia?' via '+s.slipVia:''}${s.slipNo?' to '+s.slipNo:''}.`);if(s.extra)q.push(s.extra);$('pTerms').textContent=q.join('\n\n');$('pFooterRef').textContent=s.number;renderMenu();localStorage.setItem(K,JSON.stringify(s));$('history').textContent='Current document is saved automatically in this browser.'}
function addItem(){s.items.push({description:'',qty:1,unit:'Pax',price:0});draw();render()}function removeItem(n){if(s.items.length>1){s.items.splice(n,1);draw();render()}}function saveDoc(m=true){read();localStorage.setItem(K,JSON.stringify(s));if(m)alert(s.number+' saved')}function newDoc(){if(confirm('Create a new quotation?'))fresh()}function convertDoc(){let x=prompt('Convert to quotation, proforma, or invoice','invoice'),m={quotation:'quotation',proforma:'proforma','proforma invoice':'proforma',invoice:'invoice'}[(x||'').toLowerCase().trim()];if(m){let o=JSON.parse(JSON.stringify(s));fresh(m);['customer','phone','address','serviceType','serviceFrom','serviceTo','servicePax','serviceLabel','items','menu','bank','account','slipVia','slipNo','extra'].forEach(k=>s[k]=o[k]);bind()}}function savePDF(){saveDoc(false);document.title=s.number.replace('/','-')+'-'+s.customer;print()}
$('items').addEventListener('input',e=>{let r=e.target.closest('.item'),k=e.target.dataset.k;if(!r||!k)return;s.items[+r.dataset.i][k]=['qty','price'].includes(k)?Number(e.target.value||0):e.target.value;render()});document.querySelector('.editor').addEventListener('input',e=>{if(!e.target.closest('#items'))render()});document.querySelector('.editor').addEventListener('change',e=>{if(e.target.id!='type')render()});$('type').addEventListener('change',e=>{let n=e.target.value,o=JSON.parse(JSON.stringify(s));fresh(n);['customer','phone','address','serviceType','serviceFrom','serviceTo','servicePax','serviceLabel','items','menu'].forEach(k=>s[k]=o[k]);bind()});
let st=document.createElement('style');st.textContent='.service-fields{margin-top:10px;padding:10px;background:var(--accent-soft);border-radius:8px}.service-fields.disabled{display:none}.service-banner{margin-top:6mm;display:grid;grid-template-columns:1fr auto;gap:8mm;align-items:center;padding:5mm 6mm;border-radius:4mm;background:var(--accent);color:#fff}.service-title{font-family:Georgia,serif;font-size:16pt;font-weight:700}.service-kicker{font-size:7pt;text-transform:uppercase}.pax-block{text-align:center;padding-left:5mm;border-left:1px solid #ffffff55}.pax-block strong{display:block;font-size:22pt}.menu-service{margin-top:5mm;display:flex;justify-content:space-between;padding:3mm 4mm;background:var(--sand);border-radius:3mm;font-size:8pt}';document.head.appendChild(st);
let d=localStorage.getItem(K);if(d){try{s=JSON.parse(d);if(s.serviceFrom===undefined)fresh();else bind()}catch{fresh()}}else fresh();