function parseMenu(text){const days=[];let current=null;for(const line of String(text||'').split(/\r?\n/).map(v=>v.trim()).filter(Boolean)){if(/^Day\s+\d+/i.test(line)){current={label:line,meals:[]};days.push(current);continue}if(!current)continue;const m=line.match(/^(.+?)(?:\s+(\d{1,2}:\d{2}-\d{1,2}:\d{2}))?:\s*(.*)$/);if(m)current.meals.push({name:m[1].trim(),time:m[2]||'',items:m[3].trim()})}return days}
function pdfTypeTitle(d){return CFG[d.document_type]?.label||'Document'}
function renderPrint(d){const c=calc(d),set=S.settings,t=CFG[d.document_type];const isReceipt=d.document_type==='receipt';let pay='';if(d.document_type==='invoice')pay=`<div class="pdf-pay"><div><div class="label">Paid</div><strong>${money(c.paid,d.currency)}</strong><p>${d.payment_reference?`Reference: ${esc(d.payment_reference)}`:'Payments recorded on this invoice.'}</p></div><div><div class="label">Balance Due</div><strong>${money(c.balance,d.currency)}</strong><p>${c.balance<=0?'Paid in full.':'Amount remaining.'}</p></div></div>`;else if(d.use_advance&&!isReceipt){const adv=c.total*num(d.advance_percent)/100;pay=`<div class="pdf-pay"><div><div class="label">Advance Required</div><strong>${money(adv,d.currency)}</strong><p>${d.advance_due?`Due on or before ${esc(dateLong(d.advance_due))}`:'Required to confirm the booking.'}</p></div><div><div class="label">Remaining Balance</div><strong>${money(c.total-adv,d.currency)}</strong><p>Balance payable as agreed before service or delivery.</p></div></div>`}else if(isReceipt)pay=`<div class="pdf-pay"><div><div class="label">Amount Received</div><strong>${money(c.total,d.currency)}</strong><p>${d.payment_reference?`Reference: ${esc(d.payment_reference)}`:'Payment received.'}</p></div><div><div class="label">Related Document</div><strong>${esc(sourceNo(d.source_document_id)||'Standalone')}</strong><p>Official payment receipt.</p></div></div>`;
 let bankInstruction=isReceipt?'':`Bank Transfer: ${FIXED.bank} - Account No.: ${FIXED.account}\nAfter payment, send the payment slip via Viber to ${FIXED.viber}.`;
 let terms=[d.extra_terms,bankInstruction].filter(Boolean).join('\n\n');
 const dueRow=t.due&&d.expires_on?`<b>${esc(t.due)}</b><span>${esc(dateLong(d.expires_on))}</span>`:'';
 const event=d.service_enabled?`<div class="pdf-event"><div><div class="k">Event / Service</div><h3>${esc(d.event_name||d.service_type||'Service')}</h3><p>${esc(period(d.service_from,d.service_to))}${d.venue?` - ${esc(d.venue)}`:''}</p></div><div class="pax">${num(d.service_pax).toLocaleString()}<small>Pax</small></div></div>`:'';
 const subLabel=d.gst_mode==='inclusive'?'Net Amount':'Sub Total';
 let summary=`<table class="pdf-summary"><tr><td>${subLabel}</td><td>${moneyOnly(d.gst_mode==='inclusive'?c.net:c.raw)}</td></tr>${c.discount?`<tr><td>Discount</td><td>${moneyOnly(c.discount)}</td></tr>`:''}${c.gst||d.show_gst?`<tr><td>GST @ ${num(d.gst_rate)}%</td><td>${moneyOnly(c.gst)}</td></tr>`:''}<tr class="grand"><td>Total (${esc(d.currency)})</td><td>${moneyOnly(c.total)}</td></tr></table>`;
 const audit=`<div class="pdf-audit"><span>Created by: <b>${esc(d.created_by_name||S.preparedBy||'')}</b>${d.created_at?` - ${new Date(d.created_at).toLocaleString()}`:''}</span><span>${d.updated_by_name?`Last updated by: <b>${esc(d.updated_by_name)}</b>`:''} ${d.version?`- Version ${d.version}`:''}</span></div>`;
 const main=`<section class="pdf-page"><div class="pdf-topline"></div><header class="pdf-head"><div class="pdf-company"><h1>${esc(set.company_name)}</h1><p>${esc(set.address)}<br>${esc(set.email)}<br>Hotline: ${FIXED.hotline}</p></div><div class="pdf-doc"><div class="type">${esc(pdfTypeTitle(d))}</div><div class="no">${esc(d.document_number)}</div><span class="status">${esc(d.status)}</span></div></header><div class="pdf-rule"></div><div class="pdf-info"><div class="pdf-card"><div class="label">Prepared For</div><div class="name">${esc(d.customer_name||'Customer')}</div><p>${esc(d.customer_phone||'')}${d.customer_address?`<br>${esc(d.customer_address)}`:''}</p></div><div class="pdf-card"><div class="label">Document Details</div><div class="pdf-meta"><b>Number</b><span>${esc(d.document_number)}</span><b>Issue Date</b><span>${esc(dateLong(d.creation_date)||'Not set')}</span>${dueRow}</div></div></div>${event}<table class="pdf-table"><thead><tr><th>#</th><th>Description</th><th>Qty</th><th>Unit</th><th class="num">Rate</th><th class="num">Amount</th></tr></thead><tbody>${(d.items||[]).map((i,n)=>`<tr><td>${n+1}</td><td><b>${esc(i.description||'')}</b></td><td>${num(i.qty).toLocaleString()}</td><td>${esc(i.unit||'')}</td><td class="num">${moneyOnly(i.price)}</td><td class="num">${moneyOnly(num(i.qty)*num(i.price))}</td></tr>`).join('')}</tbody></table>${summary}${pay}${terms?`<div class="pdf-terms"><h4>Payment & Terms</h4><p>${esc(terms)}</p></div>`:''}${audit}<footer class="pdf-footer"><span>${esc(set.footer||defaultSettings.footer)}</span><span>${esc(d.document_number)}</span></footer></section>`;
 let menu='';if(d.include_menu&&String(d.menu_text||'').trim()&&!isReceipt){const days=parseMenu(d.menu_text);menu=`<section class="pdf-page"><div class="pdf-topline"></div><header class="pdf-head"><div class="pdf-company"><h1>${esc(set.company_name)}</h1><p>Catering Menu<br>Hotline: ${FIXED.hotline}</p></div><div class="pdf-doc"><div class="no">${esc(d.document_number)}</div></div></header><h2 class="pdf-menu-title">${esc(d.menu_title||'CATERING MENU')}</h2><div class="pdf-menu-sub">${esc(d.customer_name||'')}${d.service_enabled?` - ${esc(period(d.service_from,d.service_to))}`:''}</div><div class="pdf-menu-grid">${days.map((day,i)=>{let dt=d.service_from?new Date(d.service_from+'T00:00:00'):null;if(dt)dt.setDate(dt.getDate()+i);const title=dt?`DAY ${i+1} - ${dateLong(dt.toISOString().slice(0,10)).toUpperCase()}`:`DAY ${i+1}`;return `<section class="pdf-day"><div class="pdf-day-head"><small>Service Schedule</small><h3>${esc(title)}</h3></div>${day.meals.map(m=>`<div class="pdf-meal"><div><b>${esc(m.name)}</b>${m.time?`<time>${esc(m.time)}</time>`:''}</div><p class="${/not required/i.test(m.items)?'off':''}">${esc(m.items)}</p></div>`).join('')}</section>`}).join('')}</div><footer class="pdf-footer"><span>${esc(set.footer||defaultSettings.footer)}</span><span>Menu Attachment</span></footer></section>`}
 $('#printRoot').innerHTML=main+menu;
}
async function exportPDF(){readEditor();if(S.current.id){const ok=await saveCurrent(false);if(!ok)return}else{const ok=await saveCurrent(false);if(!ok)return}renderPrint(S.current);const old=document.title;document.title=`${S.current.document_number}-${S.current.customer_name||'document'}`;setTimeout(()=>{window.print();setTimeout(()=>{document.title=old},250)},50)}

function updateEditorSaveState(){const el=$('[data-save-state]');if(!el||!S.current)return;const dirty=!!S.editorDirty;el.textContent=dirty?'Unsaved changes':(S.current.id?'All changes saved':'Not saved yet');el.classList.toggle('dirty',dirty);el.classList.toggle('saved',!dirty&&!!S.current.id);el.classList.toggle('new',!dirty&&!S.current.id)}
function markEditorDirty(){S.editorDirty=true;updateEditorSaveState()}
function bindDynamic(){
 $$('[data-new]').forEach(b=>b.onclick=openModal);$$('[data-go-docs]').forEach(b=>b.onclick=()=>goDocuments('all'));$$('[data-open]').forEach(x=>x.onclick=()=>{const d=S.docs.find(v=>v.id===x.dataset.open);if(d){S.editorDirty=false;openEditor(d)}});$$('[data-doc-filter]').forEach(b=>b.onclick=()=>goDocuments(b.dataset.docFilter));
 const search=$('#docSearch');if(search)search.oninput=e=>{S.search=e.target.value;render();const n=$('#docSearch');if(n){n.focus();n.setSelectionRange(S.search.length,S.search.length)}};
 const back=$('[data-back]');if(back)back.onclick=()=>goDocuments(S.current?.document_type||'all');
 const save=$('[data-save]');if(save)save.onclick=()=>saveCurrent(true);const pdf=$('[data-pdf]');if(pdf)pdf.onclick=exportPDF;
 const dup=$('[data-duplicate]');if(dup)dup.onclick=duplicateCurrent;$$('[data-convert]').forEach(b=>b.onclick=()=>convertCurrent(b.dataset.convert));const cr=$('[data-create-receipt]');if(cr)cr.onclick=receiptFromCurrent;
 $$('[data-section-toggle]').forEach(b=>b.onclick=()=>{const card=b.closest('.optional-card');if(!card)return;const willOpen=card.classList.contains('collapsed');card.classList.toggle('collapsed',!willOpen);b.setAttribute('aria-expanded',willOpen?'true':'false');b.textContent=willOpen?'Hide':'Show';const key=card.dataset.sectionKey;if(key)localStorage.setItem(key,willOpen?'open':'closed')});
 $$('[data-field]').forEach(el=>{el.oninput=()=>{readEditor();markEditorDirty();renderEditorSoft()};el.onchange=()=>{readEditor();markEditorDirty();render()}});
 const add=$('[data-add-item]');if(add)add.onclick=()=>{readEditor();S.current.items.push({description:'',qty:1,unit:'Pax',price:0});markEditorDirty();render()};$$('[data-remove-item]').forEach(b=>b.onclick=()=>{readEditor();if(S.current.items.length>1)S.current.items.splice(+b.dataset.removeItem,1);markEditorDirty();render()});$$('[data-item-field]').forEach(el=>el.oninput=()=>{readEditor();markEditorDirty();renderEditorSoft()});
 const ss=$('[data-save-settings]');if(ss)ss.onclick=saveSettings;
}
function renderEditorSoft(){const d=S.current;if(!d)return;const c=calc(d);const total=$('.totals-mini b');if(total)total.textContent=money(c.total,d.currency);$$('[data-item]').forEach((row,i)=>{const a=row.querySelector('.amount');if(a)a.textContent=moneyOnly(num(d.items[i]?.qty)*num(d.items[i]?.price))});const preview=$('.paper-mini');if(preview){const holder=preview.parentElement;const tmp=document.createElement('div');tmp.innerHTML=miniPreview(d);holder.replaceChild(tmp.firstElementChild,preview)}const ev=$('#eventFields');if(ev)ev.classList.toggle('hidden',!d.service_enabled);const mf=$('#menuFields');if(mf)mf.classList.toggle('hidden',!d.include_menu);const af=$('#advanceFields');if(af)af.classList.toggle('hidden',!d.use_advance);updateEditorSaveState()}
function goDocuments(filter='all'){S.view='documents';S.filter=filter;S.current=null;S.editorDirty=false;S.search='';render();scrollTo(0,0)}
function openModal(){$('#newDocModal').classList.remove('hidden')}
function closeModal(){$('#newDocModal').classList.add('hidden')}

function globalEvents(){
 $('#preparedBy').value=S.preparedBy;$('#preparedBy').addEventListener('input',prepared);$('#newDocBtn').onclick=openModal;$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
 $$('[data-view]').forEach(b=>b.onclick=()=>{const v=b.dataset.view;if(v==='documents'){goDocuments(b.dataset.filter||'all')}else{S.view=v;S.current=null;S.editorDirty=false;render();scrollTo(0,0)}$('#sidebar').classList.remove('open')});
 $$('[data-close-modal]').forEach(b=>b.onclick=closeModal);$('#newDocModal').addEventListener('click',e=>{if(e.target===$('#newDocModal'))closeModal()});$$('[data-create]').forEach(b=>b.onclick=()=>{S.editorDirty=false;newDocument(b.dataset.create)});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeModal();S.convertOpen=false}})
}

globalEvents();loadAll();
