const SUPABASE_URL='https://tmupbruwmwlrmewhoodn.supabase.co';
const SUPABASE_KEY='sb_publishable_LAn1liS2zqMqlB33IQJxIw_NbgWKix1';
const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false,detectSessionInUrl:false}});
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const money=(v,c='MVR')=>`${c} ${num(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const moneyOnly=v=>num(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const isoToday=()=>new Date().toISOString().slice(0,10);
const dateShort=v=>v?new Date(v+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}):'';
const dateTiny=v=>v?new Date(v+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'short'}):'';
const dateLong=v=>v?new Date(v+'T00:00:00').toLocaleDateString('en-GB',{day:'2-digit',month:'long',year:'numeric'}):'';
const CFG={quotation:{label:'Quotation',plural:'Quotations',short:'QT',due:'Valid Until',statuses:['Draft','Sent','Accepted','Expired','Cancelled']},proforma:{label:'Proforma Invoice',plural:'Proforma Invoices',short:'PI',due:'Valid Until',statuses:['Draft','Sent','Awaiting Payment','Part Paid','Paid','Cancelled']},invoice:{label:'Invoice',plural:'Invoices',short:'INV',due:'Due Date',statuses:['Draft','Sent','Part Paid','Paid','Overdue','Cancelled']},receipt:{label:'Receipt',plural:'Receipts',short:'RC',due:'',statuses:['Issued','Cancelled']}};
const FIXED={bank:'Bank of Maldives (BML)',account:'7730000796560',viber:'7667734',hotline:'9990453'};
const defaultSettings={company_name:"Cafe' White Saffron",address:'Villimale, Maldives',phone:FIXED.hotline,email:'whitesaffron2025@gmail.com',bank:FIXED.bank,account_name:"Cafe' White Saffron",account_number:FIXED.account,viber:FIXED.viber,currency:'MVR',default_validity_days:7,quotation_terms:'',invoice_terms:'',footer:"Cafe' White Saffron - Hotline 9990453"};
const S={view:'dashboard',filter:'all',docs:[],current:null,settings:{...defaultSettings},preparedBy:localStorage.getItem('quo_prepared_by')||'',search:'',loading:true,convertOpen:false};
function calc(d){const raw=(d.items||[]).reduce((a,i)=>a+num(i.qty)*num(i.price),0);const discount=Math.min(num(d.discount),raw),base=raw-discount,rate=num(d.gst_rate),mode=d.gst_mode||'none';let gst=0,net=base,total=base;if(mode==='exclusive'){gst=base*rate/100;total=base+gst}if(mode==='inclusive'&&rate){gst=base-base/(1+rate/100);net=base-gst;total=base}return{raw,discount,base,gst,net,total,paid:num(d.paid_amount),balance:Math.max(total-num(d.paid_amount),0)}}
function statusClass(v){return String(v||'draft').toLowerCase().replaceAll(' ','-')}
function period(a,b){if(!a)return'';if(!b||a===b)return dateLong(a);const x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00');if(x.getMonth()===y.getMonth()&&x.getFullYear()===y.getFullYear())return `${x.getDate()}-${y.getDate()} ${x.toLocaleDateString('en-GB',{month:'long'})} ${x.getFullYear()}`;return `${dateLong(a)} - ${dateLong(b)}`}
function titleForView(){if(S.view==='dashboard')return['QUO','Dashboard'];if(S.view==='customers')return['DIRECTORY','Customers'];if(S.view==='settings')return['SYSTEM','Settings'];if(S.view==='editor')return['DOCUMENT','Editor'];const f=S.filter==='all'?'All Documents':CFG[S.filter]?.plural||'Documents';return['DOCUMENTS',f]}
function setTop(){const [e,t]=titleForView();$('#topEyebrow').textContent=e;$('#topTitle').textContent=t}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');clearTimeout(toast._t);toast._t=setTimeout(()=>t.classList.add('hidden'),2400)}
function prepared(){const n=$('#preparedBy').value.trim();S.preparedBy=n;localStorage.setItem('quo_prepared_by',n);return n}
async function loadAll(){S.loading=true;render();const [dr,sr]=await Promise.all([sb.from('quo_documents').select('*').order('updated_at',{ascending:false}).limit(500),sb.from('quo_settings').select('*').eq('id',1).maybeSingle()]);if(dr.error){console.error(dr.error);toast('Could not load documents')}else S.docs=dr.data||[];if(!sr.error&&sr.data)S.settings={...defaultSettings,...sr.data,bank:FIXED.bank,account_number:FIXED.account,viber:FIXED.viber,phone:FIXED.hotline};S.loading=false;render()}
function render(){setTop();setActiveNav();if(S.loading){$('#view').innerHTML='<div class="panel"><div class="empty">Loading Quo...</div></div>';return}const fn={dashboard:renderDashboard,documents:renderDocuments,customers:renderCustomers,settings:renderSettings,editor:renderEditor}[S.view]||renderDashboard;$('#view').innerHTML=fn();bindDynamic()}
function setActiveNav(){$$('[data-view]').forEach(b=>{const same=b.dataset.view===S.view||(S.view==='editor'&&b.dataset.view==='documents');const filterOk=!b.dataset.filter||S.filter===b.dataset.filter||(S.view==='editor'&&b.dataset.filter==='all');b.classList.toggle('active',same&&filterOk)})}
function pageHead(title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow">WHITE SAFFRON DOCUMENTS</div><h2>${esc(title)}</h2><p>${esc(desc)}</p></div><div class="page-actions">${actions}</div></div>`}
function kpi(label,value,sub,glyph,cls=''){return `<article class="kpi ${cls}"><div class="label"><span>${esc(label)}</span><i class="glyph">${esc(glyph)}</i></div><strong>${value}</strong><small>${esc(sub)}</small></article>`}
function renderDashboard(){const q=S.docs.filter(d=>d.document_type==='quotation'),p=S.docs.filter(d=>d.document_type==='proforma'),inv=S.docs.filter(d=>d.document_type==='invoice');const qAwait=q.filter(d=>['Draft','Sent'].includes(d.status)).length;const pAwait=p.filter(d=>calc(d).balance>0&&d.status!=='Cancelled').length;const iPaid=inv.filter(d=>calc(d).balance<=0||d.status==='Paid').length;const outstanding=[...p,...inv].filter(d=>d.status!=='Cancelled').reduce((a,d)=>a+calc(d).balance,0);const outDocs=[...p,...inv].filter(d=>d.status!=='Cancelled'&&calc(d).balance>0).length;const recent=S.docs.slice(0,8);const today=isoToday();const active=S.docs.filter(d=>d.service_enabled&&d.service_to&&d.service_to>=today&&d.status!=='Cancelled').sort((a,b)=>String(a.service_from).localeCompare(String(b.service_from))).slice(0,5);return pageHead('Welcome back','Create, send and track White Saffron commercial documents without ERP clutter.','<button class="btn primary" data-new>+ New Document</button>')+`<section class="kpis">${kpi('Quotations',q.length,`${qAwait} awaiting action`,'QT')}${kpi('Proforma',p.length,`${pAwait} awaiting payment`,'PI')}${kpi('Invoices',inv.length,`${iPaid} paid`,'INV')}${kpi('Outstanding',money(outstanding,S.settings.currency),`${outDocs} documents`,'MVR','money')}</section><section class="dashboard-grid"><div class="panel"><div class="panel-head"><h3>Recent Documents</h3><button data-go-docs>View all</button></div>${tableDocs(recent,true)}</div><div class="panel"><div class="panel-head"><h3>Upcoming / Active</h3></div><div class="upcoming">${active.length?active.map(eventCard).join(''):'<div class="empty">No upcoming catering services.</div>'}</div></div></section>`}
function eventCard(d){const from=d.service_from?new Date(d.service_from+'T00:00:00'):null;const mon=from?from.toLocaleDateString('en-GB',{month:'short'}):'';const day=from?from.getDate():'';return `<div class="event-card" data-open="${d.id}"><div class="event-date"><b>${day}</b><span>${esc(mon)}</span></div><div><h4>${esc(d.customer_name||'Customer')}</h4><p>${esc(period(d.service_from,d.service_to))}<br>${num(d.service_pax).toLocaleString()} Pax - ${esc(d.document_number)}</p></div></div>`}
function tableDocs(rows,compact=false){if(!rows.length)return '<div class="empty">No documents found.</div>';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Document</th><th>Customer</th><th>Date</th><th class="num">Total</th><th>Status</th></tr></thead><tbody>${rows.map(d=>{const c=calc(d);return `<tr data-open="${d.id}"><td><strong>${esc(d.document_number)}</strong><span class="subline">${esc(CFG[d.document_type]?.label||d.document_type)}</span></td><td>${esc(d.customer_name||'No customer')}</td><td>${esc(dateTiny(d.creation_date)||'-')}</td><td class="num">${moneyOnly(c.total)}</td><td><span class="badge ${statusClass(d.status)}">${esc(d.status||'Draft')}</span></td></tr>`}).join('')}</tbody></table></div>`}
function renderDocuments(){const label=S.filter==='all'?'All Documents':CFG[S.filter].plural;let rows=S.filter==='all'?S.docs:S.docs.filter(d=>d.document_type===S.filter);const q=S.search.trim().toLowerCase();if(q)rows=rows.filter(d=>[d.document_number,d.customer_name,d.customer_phone,d.status].some(v=>String(v||'').toLowerCase().includes(q)));const chips=['all','quotation','proforma','invoice','receipt'].map(k=>`<button class="chip ${S.filter===k?'active':''}" data-doc-filter="${k}">${k==='all'?'All':CFG[k].label}</button>`).join('');return pageHead(label,'Search and open every commercial document from one clean document engine.','<button class="btn primary" data-new>+ New Document</button>')+`<div class="toolbar-row"><label class="search"><input id="docSearch" value="${esc(S.search)}" placeholder="Search document, customer or status..."></label><div class="chips">${chips}</div></div><div class="panel">${tableDocs(rows)}</div>`}
function uniqueCustomers(){const map=new Map();for(const d of S.docs){const key=String(d.customer_name||'').trim().toLowerCase();if(!key)continue;const c=calc(d),old=map.get(key)||{name:d.customer_name,phone:d.customer_phone,address:d.customer_address,count:0,total:0,outstanding:0,last:''};old.count++;old.total+=c.total;if(['invoice','proforma'].includes(d.document_type)&&d.status!=='Cancelled')old.outstanding+=c.balance;if(String(d.updated_at||'')>old.last){old.last=d.updated_at;old.phone=d.customer_phone||old.phone;old.address=d.customer_address||old.address}map.set(key,old)}return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name))}
function renderCustomers(){const rows=uniqueCustomers();return pageHead('Customers','Customer directory is built automatically from saved documents. No separate CRM is required.')+`<div class="customer-grid">${rows.length?rows.map(c=>`<article class="customer-card"><b>${esc(c.name)}</b><p>${esc(c.phone||'No phone')}<br>${esc(c.address||'')}</p><div class="stat">${c.count} documents - ${money(c.outstanding,S.settings.currency)} outstanding</div></article>`).join(''):'<div class="panel"><div class="empty">Customers will appear after documents are saved.</div></div>'}</div>`}
