function renderEditor(){
 const d=S.current;if(!d)return renderDocuments();const t=CFG[d.document_type],c=calc(d),isReceipt=d.document_type==='receipt';
 let convert=[];if(d.document_type==='quotation')convert=[['proforma','Convert to Proforma Invoice'],['invoice','Convert to Invoice']];if(d.document_type==='proforma')convert=[['invoice','Convert to Invoice']];
 const convertButton=convert.length?`<div class="split-wrap"><button class="btn" data-toggle-convert>Convert ▾</button><div class="convert-menu ${S.convertOpen?'':'hidden'}">${convert.map(([k,l])=>`<button data-convert="${k}">${l}</button>`).join('')}</div></div>`:'';
 const receiptButton=d.document_type==='invoice'&&d.id?'<button class="btn" data-create-receipt>Create Receipt</button>':'';
 return `<div class="editor-top"><button class="back-btn" data-back>← Documents</button><div class="editor-title"><div class="eyebrow">${esc(t.label.toUpperCase())}</div><h2>${esc(d.document_number)}</h2><p>${esc(d.customer_name||'New document')} ${d.id?`- Version ${d.version||1}`:'- Unsaved'}</p></div><div class="editor-actions"><button class="btn" data-duplicate>Duplicate</button>${convertButton}${receiptButton}<button class="btn primary" data-save>${d.id?'Update':'Save'}</button><button class="btn" data-pdf>Export PDF</button></div></div>
 <div class="editor-shell"><div class="editor-main">
  ${editorCard('01','Document',`<div class="form-grid three"><div class="field"><label>Type</label><input value="${esc(t.label)}" readonly></div><div class="field"><label>Number</label><input value="${esc(d.document_number)}" readonly></div><div class="field"><label>Status</label><select data-field="status">${editorStatusOptions(d)}</select></div><div class="field"><label>Issue Date</label><input data-field="creation_date" type="date" value="${esc(d.creation_date||'')}"></div>${t.due?`<div class="field"><label>${esc(t.due)}</label><input data-field="expires_on" type="date" value="${esc(d.expires_on||'')}"></div>`:''}<div class="field"><label>Currency</label><input data-field="currency" value="${esc(d.currency||'MVR')}"></div></div>`)}
  ${editorCard('02','Customer',`<div class="form-grid"><div class="field"><label>Customer</label><input data-field="customer_name" value="${esc(d.customer_name||'')}" placeholder="Customer or organisation"></div><div class="field"><label>Phone</label><input data-field="customer_phone" value="${esc(d.customer_phone||'')}"></div><div class="field full"><label>Address / Reference</label><input data-field="customer_address" value="${esc(d.customer_address||'')}"></div></div>`)}
  ${!isReceipt?editorCard('03','Event / Service',eventFields(d)):''}
  ${editorCard(isReceipt?'03':'04','Items',itemEditor(d))}
  ${!isReceipt?editorCard('05','Menu',`<div class="switch-row"><div class="switch-copy"><b>Include Menu Page</b><span>The menu stays inside this document and becomes PDF page 2.</span></div><label class="toggle"><input data-field="include_menu" type="checkbox" ${d.include_menu?'checked':''}><i></i></label></div><div id="menuFields" class="${d.include_menu?'':'hidden'}"><div class="form-grid"><div class="field full"><label>Menu Title</label><input data-field="menu_title" value="${esc(d.menu_title||'CATERING MENU')}"></div><div class="field full"><label>Menu Schedule</label><textarea data-field="menu_text" placeholder="Day 1\nBreakfast 07:00-08:00: ...\nLunch 12:00-14:00: ...\n\nDay 2\nBreakfast 07:00-08:00: ...">${esc(d.menu_text||'')}</textarea></div></div></div>`):''}
  ${editorCard(isReceipt?'04':'06','Payment',paymentSection(d))}
  ${editorCard(isReceipt?'05':'07','Notes & Terms',`<div class="field full"><label>Notes / Terms</label><textarea data-field="extra_terms" placeholder="Optional document terms or notes">${esc(d.extra_terms||'')}</textarea></div>`)}
 </div><aside class="preview-card"><div class="preview-toolbar"><b>PDF Preview</b><span class="badge ${statusClass(d.status)}">${esc(d.status)}</span></div>${miniPreview(d)}</aside></div>`;
}
function editorCard(n,title,body){return `<section class="editor-card"><header><span class="section-no">${n}</span><h3>${esc(title)}</h3></header><div class="card-body">${body}</div></section>`}
function miniPreview(d){const c=calc(d);return `<div class="paper-mini"><div class="mini-head"><div class="mini-brand">${esc(S.settings.company_name)}<small>${esc(S.settings.address)}<br>Hotline ${FIXED.hotline}</small></div><div class="mini-doc"><b>${esc(CFG[d.document_type].label)}</b><span>${esc(d.document_number)}</span></div></div><div class="mini-info"><div class="mini-box"><div class="mini-label">Prepared For</div><div class="mini-value">${esc(d.customer_name||'Customer')}</div></div><div class="mini-box"><div class="mini-label">Issue Date</div><div class="mini-value">${esc(dateShort(d.creation_date)||'Not set')}</div></div></div>${d.service_enabled?`<div class="mini-event">${esc(d.event_name||d.service_type||'Service')} - ${esc(period(d.service_from,d.service_to))} - ${num(d.service_pax)} Pax</div>`:''}<div class="mini-lines">${(d.items||[]).slice(0,5).map(i=>`<div class="mini-line"><span>${esc(i.description||'Item')}</span><span>${num(i.qty)} ${esc(i.unit||'')}</span><b>${moneyOnly(num(i.qty)*num(i.price))}</b></div>`).join('')}</div><div class="mini-total"><span>Total</span><span>${money(c.total,d.currency)}</span></div><div class="mini-foot"><span>${esc(S.settings.footer||defaultSettings.footer)}</span><span>${esc(d.document_number)}</span></div></div>`}
function readEditor(){const d=S.current;if(!d)return;$$('[data-field]').forEach(el=>{const k=el.dataset.field;if(el.type==='checkbox')d[k]=el.checked;else if(['service_pax','gst_rate','discount','advance_percent','paid_amount'].includes(k))d[k]=num(el.value);else d[k]=el.value});$$('[data-item]').forEach(row=>{const i=+row.dataset.item;row.querySelectorAll('[data-item-field]').forEach(el=>{const k=el.dataset.itemField;d.items[i][k]=['qty','price'].includes(k)?num(el.value):el.value})})}
function payload(d){return{document_number:d.document_number,document_type:d.document_type,status:d.status,currency:d.currency,creation_date:d.creation_date||null,expires_on:d.expires_on||null,customer_name:d.customer_name||null,customer_phone:d.customer_phone||null,customer_address:d.customer_address||null,event_name:d.event_name||null,service_enabled:!!d.service_enabled,service_type:d.service_type||null,service_from:d.service_from||null,service_to:d.service_to||null,service_pax:num(d.service_pax),service_label:d.service_label||'Service Period',venue:d.venue||null,items:d.items||[],gst_mode:d.gst_mode||'none',gst_rate:num(d.gst_rate),discount:num(d.discount),show_gst:!!d.show_gst,include_menu:!!d.include_menu,menu_title:d.menu_title||null,menu_text:d.menu_text||null,use_advance:!!d.use_advance,advance_percent:num(d.advance_percent),advance_due:d.advance_due||null,bank:FIXED.bank,account_no:FIXED.account,slip_via:'Viber',slip_contact:FIXED.viber,paid_amount:num(d.paid_amount),payment_reference:d.payment_reference||null,extra_terms:d.extra_terms||null,source_document_id:d.source_document_id||null}}
async function saveCurrent(showToast=true){readEditor();const d=S.current,name=prepared(),wasNew=!d.id;if(!name){alert('Enter Prepared By before saving.');$('#preparedBy').focus();return false}if(!d.customer_name?.trim()){alert('Enter the customer name before saving.');return false}if(!(d.items||[]).some(i=>String(i.description||'').trim())){alert('Add at least one item description.');return false}if(['invoice','proforma'].includes(d.document_type)&&d.status!=='Cancelled'){const cc=calc(d);if(num(d.paid_amount)>0)d.status=num(d.paid_amount)>=cc.total?'Paid':'Part Paid'}try{if(wasNew){const year=d.creation_date?new Date(d.creation_date+'T00:00:00').getFullYear():new Date().getFullYear();const nr=await sb.rpc('next_quo_document_number_v2',{p_type:d.document_type,p_year:year});if(nr.error)throw nr.error;d.document_number=nr.data;const r=await sb.from('quo_documents').insert({...payload(d),created_by:null,created_by_name:name,updated_by:null,updated_by_name:name}).select('*').single();if(r.error)throw r.error;S.current={...d,...r.data}}else{const p=payload(d);delete p.document_number;delete p.document_type;const r=await sb.from('quo_documents').update({...p,updated_by:null,updated_by_name:name}).eq('id',d.id).select('*').single();if(r.error)throw r.error;S.current={...d,...r.data}}if(wasNew&&S.current.document_type==='receipt'&&S.current.source_document_id)await applyReceiptToSource(S.current,name);await refreshDocs();if(showToast)toast(`${S.current.document_number} saved`);render();return true}catch(e){console.error(e);alert('Save failed: '+e.message);return false}}
async function applyReceiptToSource(receipt,name){const src=S.docs.find(x=>x.id===receipt.source_document_id);if(!src||!['invoice','proforma'].includes(src.document_type))return;const sc=calc(src),received=calc(receipt).total,newPaid=Math.min(sc.total,num(src.paid_amount)+received),status=newPaid>=sc.total?'Paid':'Part Paid';const r=await sb.from('quo_documents').update({paid_amount:newPaid,status,updated_by:null,updated_by_name:name}).eq('id',src.id);if(r.error)console.warn('Receipt saved but source payment update failed',r.error)}
async function refreshDocs(){const r=await sb.from('quo_documents').select('*').order('updated_at',{ascending:false}).limit(500);if(!r.error)S.docs=r.data||[]}
function duplicateCurrent(){readEditor();const copy=blankDoc(S.current.document_type,S.current);copy.source_document_id=null;openEditor(copy)}
function convertCurrent(type){readEditor();const copy=blankDoc(type,S.current);copy.source_document_id=S.current.id||null;if(type==='invoice'){copy.use_advance=false;copy.paid_amount=0;copy.extra_terms=S.settings.invoice_terms||copy.extra_terms}openEditor(copy)}
function receiptFromCurrent(){readEditor();const src=S.current,c=calc(src);if(c.balance<=0)return alert('This invoice is already fully paid.');const raw=prompt('Payment amount received',String(c.balance.toFixed(2)));if(raw===null)return;const amt=num(raw);if(amt<=0)return alert('Enter a payment amount greater than 0.');const r=blankDoc('receipt');r.customer_name=src.customer_name;r.customer_phone=src.customer_phone;r.customer_address=src.customer_address;r.currency=src.currency;r.creation_date=isoToday();r.source_document_id=src.id;r.items=[{description:`Payment received for ${src.document_number}`,qty:1,unit:'Payment',price:amt}];r.paid_amount=amt;r.extra_terms=`Payment received against ${src.document_number}.`;openEditor(r)}
async function saveSettings(){const p={};$$('[data-setting]').forEach(el=>p[el.dataset.setting]=el.type==='number'?num(el.value):el.value);p.phone=FIXED.hotline;p.bank=FIXED.bank;p.account_number=FIXED.account;p.viber=FIXED.viber;p.updated_at=new Date().toISOString();const r=await sb.from('quo_settings').update(p).eq('id',1).select('*').single();if(r.error)return alert('Could not save settings: '+r.error.message);S.settings={...defaultSettings,...r.data,phone:FIXED.hotline,bank:FIXED.bank,account_number:FIXED.account,viber:FIXED.viber};toast('Settings saved');render()}
