-- Quo v72: Admin-only catering supply allocations.
-- Replaces whole-bill costing in the UI with quotation -> bill -> bill item -> allocated quantity.
-- Structured bill items are allocated proportionally by quantity. Legacy header-only bills can be allocated manually.

create table if not exists public.quo_catering_supply_allocations (
  id bigint generated by default as identity primary key,
  quotation_id uuid not null references public.quo_documents(id) on delete cascade,
  bill_id bigint not null references public.bills(id) on delete restrict,
  bill_item_id bigint references public.bill_items(id) on delete restrict,
  source_mode text not null check (source_mode in ('structured','manual')),
  supply_name text not null,
  allocated_qty numeric(14,4) not null check (allocated_qty > 0),
  unit text not null default 'PCS',
  unit_cost numeric(14,6) not null default 0 check (unit_cost >= 0),
  allocated_cost numeric(14,2) not null default 0 check (allocated_cost >= 0),
  note text,
  allocated_by uuid not null references auth.users(id) on delete restrict,
  allocated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quo_supply_structured_item_required check (
    (source_mode='structured' and bill_item_id is not null)
    or (source_mode='manual' and bill_item_id is null)
  )
);

create unique index if not exists quo_catering_supply_structured_quote_item_uidx
  on public.quo_catering_supply_allocations(quotation_id,bill_item_id)
  where source_mode='structured';
create index if not exists quo_catering_supply_quote_idx
  on public.quo_catering_supply_allocations(quotation_id,allocated_at desc);
create index if not exists quo_catering_supply_bill_idx
  on public.quo_catering_supply_allocations(bill_id,allocated_at desc);
create index if not exists quo_catering_supply_item_idx
  on public.quo_catering_supply_allocations(bill_item_id)
  where bill_item_id is not null;

alter table public.quo_catering_supply_allocations enable row level security;

drop policy if exists quo_catering_supply_admin_select on public.quo_catering_supply_allocations;
create policy quo_catering_supply_admin_select
on public.quo_catering_supply_allocations
for select to authenticated
using (public.quo_is_admin());

revoke all on public.quo_catering_supply_allocations from anon;
revoke insert,update,delete on public.quo_catering_supply_allocations from authenticated;
grant select on public.quo_catering_supply_allocations to authenticated;

create or replace function public.quo_get_catering_supplies(p_quotation_id uuid)
returns table(
  allocation_id bigint,
  bill_id bigint,
  bill_item_id bigint,
  source_mode text,
  bill_no text,
  bill_day date,
  vendor text,
  supply_name text,
  purchased_qty numeric,
  allocated_qty numeric,
  remaining_qty numeric,
  unit text,
  unit_cost numeric,
  allocated_cost numeric,
  payment_status text,
  note text,
  allocated_at timestamptz
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  if not exists(select 1 from public.quo_documents q where q.id=p_quotation_id and q.document_type='quotation' and q.deleted_at is null)
    then raise exception 'Quotation not found'; end if;

  return query
  select
    a.id,
    a.bill_id,
    a.bill_item_id,
    a.source_mode,
    coalesce(nullif(b.bill_no,''),nullif(b."Bill No",''),'#'||b.id::text),
    coalesce(b.bill_day,case when coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''),'') ~ '^\d{4}-\d{2}-\d{2}$' then coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''))::date else null end),
    coalesce(nullif(b.vendor,''),nullif(b."Vendor",''),'Unknown supplier'),
    a.supply_name,
    case when a.source_mode='structured' then bi.quantity else null end,
    a.allocated_qty,
    case when a.source_mode='structured' then greatest(coalesce(bi.quantity,0)-coalesce((select sum(x.allocated_qty) from public.quo_catering_supply_allocations x where x.bill_item_id=a.bill_item_id),0),0) else null end,
    a.unit,
    a.unit_cost,
    a.allocated_cost,
    coalesce(nullif(b.payment_status,''),'Pending'),
    a.note,
    a.allocated_at
  from public.quo_catering_supply_allocations a
  join public.bills b on b.id=a.bill_id
  left join public.bill_items bi on bi.id=a.bill_item_id
  where a.quotation_id=p_quotation_id and b.deleted_at is null
  order by coalesce(b.bill_day,b.created_at::date) desc,b.id desc,a.id desc;
end;
$func$;

create or replace function public.quo_search_catering_supply_sources(
  p_quotation_id uuid,
  p_search text default null,
  p_limit integer default 120
)
returns table(
  source_mode text,
  bill_id bigint,
  bill_item_id bigint,
  bill_no text,
  bill_day date,
  vendor text,
  supply_name text,
  purchased_qty numeric,
  allocated_elsewhere numeric,
  available_qty numeric,
  unit text,
  unit_cost numeric,
  line_cost numeric,
  bill_amount numeric,
  payment_status text
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_search text:=lower(btrim(coalesce(p_search,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,120),250));
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  if not exists(select 1 from public.quo_documents q where q.id=p_quotation_id and q.document_type='quotation' and q.deleted_at is null and q.status in ('Confirmed','Accepted'))
    then raise exception 'Supplies can be allocated only to a confirmed quotation'; end if;

  return query
  with structured as (
    select
      'structured'::text as source_mode,
      b.id as bill_id,
      bi.id as bill_item_id,
      coalesce(nullif(b.bill_no,''),nullif(b."Bill No",''),'#'||b.id::text) as bill_no,
      coalesce(b.bill_day,case when coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''),'') ~ '^\d{4}-\d{2}-\d{2}$' then coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''))::date else null end) as bill_day,
      coalesce(nullif(b.vendor,''),nullif(b."Vendor",''),'Unknown supplier') as vendor,
      coalesce(nullif(bi.description,''),nullif(bi.item_name,''),'Item') as supply_name,
      coalesce(bi.quantity,0)::numeric as purchased_qty,
      coalesce((select sum(a.allocated_qty) from public.quo_catering_supply_allocations a where a.bill_item_id=bi.id and a.quotation_id<>p_quotation_id),0)::numeric as allocated_elsewhere,
      greatest(coalesce(bi.quantity,0)-coalesce((select sum(a.allocated_qty) from public.quo_catering_supply_allocations a where a.bill_item_id=bi.id and a.quotation_id<>p_quotation_id),0),0)::numeric as available_qty,
      coalesce(nullif(bi.unit,''),nullif(bi.base_unit,''),'PCS') as unit,
      case when coalesce(bi.quantity,0)>0 then coalesce(nullif(bi.line_total,0),nullif(bi.net_amount,0),coalesce(bi.quantity,0)*coalesce(bi.unit_rate,0),0)/bi.quantity else coalesce(bi.unit_rate,0) end::numeric as unit_cost,
      coalesce(nullif(bi.line_total,0),nullif(bi.net_amount,0),coalesce(bi.quantity,0)*coalesce(bi.unit_rate,0),0)::numeric as line_cost,
      coalesce(b.net_amount,nullif(regexp_replace(coalesce(nullif(b.amount,''),nullif(b."Amount",''),''),'[^0-9.-]','','g'),'')::numeric,0::numeric) as bill_amount,
      coalesce(nullif(b.payment_status,''),'Pending') as payment_status
    from public.bill_items bi
    join public.bills b on b.id=bi.bill_id
    where bi.deleted_at is null and b.deleted_at is null
      and coalesce(bi.quantity,0)>0
      and (
        v_search=''
        or lower(coalesce(bi.description,bi.item_name,'')) like '%'||v_search||'%'
        or lower(coalesce(b.bill_no,b."Bill No",'')) like '%'||v_search||'%'
        or lower(coalesce(b.vendor,b."Vendor",'')) like '%'||v_search||'%'
        or lower(coalesce(b.location,b."Location",'')) like '%'||v_search||'%'
      )
  ), legacy as (
    select
      'manual'::text as source_mode,
      b.id as bill_id,
      null::bigint as bill_item_id,
      coalesce(nullif(b.bill_no,''),nullif(b."Bill No",''),'#'||b.id::text) as bill_no,
      coalesce(b.bill_day,case when coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''),'') ~ '^\d{4}-\d{2}-\d{2}$' then coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''))::date else null end) as bill_day,
      coalesce(nullif(b.vendor,''),nullif(b."Vendor",''),'Unknown supplier') as vendor,
      'Legacy bill — enter supply'::text as supply_name,
      null::numeric as purchased_qty,
      null::numeric as allocated_elsewhere,
      null::numeric as available_qty,
      null::text as unit,
      null::numeric as unit_cost,
      null::numeric as line_cost,
      coalesce(b.net_amount,nullif(regexp_replace(coalesce(nullif(b.amount,''),nullif(b."Amount",''),''),'[^0-9.-]','','g'),'')::numeric,0::numeric) as bill_amount,
      coalesce(nullif(b.payment_status,''),'Pending') as payment_status
    from public.bills b
    where b.deleted_at is null
      and not exists(select 1 from public.bill_items bi where bi.bill_id=b.id and bi.deleted_at is null)
      and (
        v_search=''
        or lower(coalesce(b.bill_no,b."Bill No",'')) like '%'||v_search||'%'
        or lower(coalesce(b.vendor,b."Vendor",'')) like '%'||v_search||'%'
        or lower(coalesce(b.location,b."Location",'')) like '%'||v_search||'%'
      )
  )
  select * from (
    select * from structured where available_qty>0
    union all
    select * from legacy
  ) s
  order by s.bill_day desc nulls last,s.bill_id desc,s.source_mode,s.supply_name
  limit v_limit;
end;
$func$;

create or replace function public.quo_allocate_structured_supply(
  p_quotation_id uuid,
  p_bill_item_id bigint,
  p_quantity numeric,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_id bigint;
  v_item public.bill_items%rowtype;
  v_bill public.bills%rowtype;
  v_used_elsewhere numeric:=0;
  v_unit_cost numeric:=0;
  v_cost numeric:=0;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  if coalesce(p_quantity,0)<=0 then raise exception 'Allocated quantity must be greater than zero'; end if;
  if not exists(select 1 from public.quo_documents q where q.id=p_quotation_id and q.document_type='quotation' and q.deleted_at is null and q.status in ('Confirmed','Accepted'))
    then raise exception 'Supplies can be allocated only to a confirmed quotation'; end if;

  select * into v_item from public.bill_items where id=p_bill_item_id and deleted_at is null;
  if not found then raise exception 'Purchase bill item not found'; end if;
  select * into v_bill from public.bills where id=v_item.bill_id and deleted_at is null;
  if not found then raise exception 'Purchase bill not found'; end if;

  select coalesce(sum(a.allocated_qty),0) into v_used_elsewhere
  from public.quo_catering_supply_allocations a
  where a.bill_item_id=p_bill_item_id and a.quotation_id<>p_quotation_id;

  if p_quantity > greatest(coalesce(v_item.quantity,0)-v_used_elsewhere,0)
    then raise exception 'Only % % remains available from this purchase item',greatest(coalesce(v_item.quantity,0)-v_used_elsewhere,0),coalesce(nullif(v_item.unit,''),'units'); end if;

  if coalesce(v_item.quantity,0)>0 then
    v_unit_cost:=coalesce(nullif(v_item.line_total,0),nullif(v_item.net_amount,0),v_item.quantity*coalesce(v_item.unit_rate,0),0)/v_item.quantity;
  else
    v_unit_cost:=coalesce(v_item.unit_rate,0);
  end if;
  v_cost:=round(p_quantity*v_unit_cost,2);

  insert into public.quo_catering_supply_allocations(
    quotation_id,bill_id,bill_item_id,source_mode,supply_name,allocated_qty,unit,unit_cost,allocated_cost,note,allocated_by
  ) values(
    p_quotation_id,v_item.bill_id,v_item.id,'structured',coalesce(nullif(v_item.description,''),nullif(v_item.item_name,''),'Item'),p_quantity,coalesce(nullif(v_item.unit,''),nullif(v_item.base_unit,''),'PCS'),v_unit_cost,v_cost,nullif(btrim(coalesce(p_note,'')),''),auth.uid()
  )
  on conflict (quotation_id,bill_item_id) where source_mode='structured'
  do update set allocated_qty=excluded.allocated_qty,unit_cost=excluded.unit_cost,allocated_cost=excluded.allocated_cost,note=coalesce(excluded.note,public.quo_catering_supply_allocations.note),allocated_by=auth.uid(),updated_at=now()
  returning id into v_id;
  return v_id;
end;
$func$;

create or replace function public.quo_allocate_manual_supply(
  p_quotation_id uuid,
  p_bill_id bigint,
  p_supply_name text,
  p_quantity numeric,
  p_unit text,
  p_allocated_cost numeric,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_id bigint;
  v_bill_amount numeric:=0;
  v_manual_total numeric:=0;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  if not exists(select 1 from public.quo_documents q where q.id=p_quotation_id and q.document_type='quotation' and q.deleted_at is null and q.status in ('Confirmed','Accepted'))
    then raise exception 'Supplies can be allocated only to a confirmed quotation'; end if;
  if not exists(select 1 from public.bills b where b.id=p_bill_id and b.deleted_at is null)
    then raise exception 'Purchase bill not found'; end if;
  if btrim(coalesce(p_supply_name,''))='' then raise exception 'Enter the supply name'; end if;
  if coalesce(p_quantity,0)<=0 then raise exception 'Quantity must be greater than zero'; end if;
  if coalesce(p_allocated_cost,0)<0 then raise exception 'Allocated cost cannot be negative'; end if;

  select coalesce(b.net_amount,nullif(regexp_replace(coalesce(nullif(b.amount,''),nullif(b."Amount",''),''),'[^0-9.-]','','g'),'')::numeric,0)
    into v_bill_amount from public.bills b where b.id=p_bill_id;
  select coalesce(sum(a.allocated_cost),0) into v_manual_total from public.quo_catering_supply_allocations a where a.bill_id=p_bill_id and a.source_mode='manual';
  if v_bill_amount>0 and v_manual_total+coalesce(p_allocated_cost,0)>v_bill_amount+0.01
    then raise exception 'Manual allocations would exceed the purchase bill total of %',v_bill_amount; end if;

  insert into public.quo_catering_supply_allocations(
    quotation_id,bill_id,bill_item_id,source_mode,supply_name,allocated_qty,unit,unit_cost,allocated_cost,note,allocated_by
  ) values(
    p_quotation_id,p_bill_id,null,'manual',btrim(p_supply_name),p_quantity,upper(coalesce(nullif(btrim(p_unit),''),'PCS')),case when p_quantity>0 then round(p_allocated_cost/p_quantity,6) else 0 end,round(p_allocated_cost,2),nullif(btrim(coalesce(p_note,'')),''),auth.uid()
  ) returning id into v_id;
  return v_id;
end;
$func$;

create or replace function public.quo_remove_catering_supply(p_allocation_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  delete from public.quo_catering_supply_allocations where id=p_allocation_id;
end;
$func$;

create or replace function public.quo_bill_catering_usage(p_bill_id bigint)
returns table(
  quotation_id uuid,
  document_number text,
  customer_name text,
  service_from date,
  service_to date,
  supply_name text,
  allocated_qty numeric,
  unit text,
  allocated_cost numeric
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  return query
  select q.id,q.document_number,q.customer_name,q.service_from,q.service_to,a.supply_name,a.allocated_qty,a.unit,a.allocated_cost
  from public.quo_catering_supply_allocations a
  join public.quo_documents q on q.id=a.quotation_id
  where a.bill_id=p_bill_id and q.deleted_at is null
  order by q.service_from nulls last,q.document_number,a.supply_name;
end;
$func$;

revoke all on function public.quo_get_catering_supplies(uuid) from public,anon;
revoke all on function public.quo_search_catering_supply_sources(uuid,text,integer) from public,anon;
revoke all on function public.quo_allocate_structured_supply(uuid,bigint,numeric,text) from public,anon;
revoke all on function public.quo_allocate_manual_supply(uuid,bigint,text,numeric,text,numeric,text) from public,anon;
revoke all on function public.quo_remove_catering_supply(bigint) from public,anon;
revoke all on function public.quo_bill_catering_usage(bigint) from public,anon;

grant execute on function public.quo_get_catering_supplies(uuid) to authenticated;
grant execute on function public.quo_search_catering_supply_sources(uuid,text,integer) to authenticated;
grant execute on function public.quo_allocate_structured_supply(uuid,bigint,numeric,text) to authenticated;
grant execute on function public.quo_allocate_manual_supply(uuid,bigint,text,numeric,text,numeric,text) to authenticated;
grant execute on function public.quo_remove_catering_supply(bigint) to authenticated;
grant execute on function public.quo_bill_catering_usage(bigint) to authenticated;
