-- Quo v73: simple Admin-only supply usage against existing Quo documents.
-- User workflow: select an existing quotation/invoice -> enter supply -> save.
-- This intentionally removes the more complex purchase-bill allocation model introduced in v71/v72.

-- The v71/v72 tables were never used in production (0 records) and are removed to keep one clear model.
drop function if exists public.quo_get_purchase_bill_links(uuid);
drop function if exists public.quo_purchase_bill_candidates(uuid,text,integer);
drop function if exists public.quo_link_purchase_bill(uuid,bigint,text);
drop function if exists public.quo_unlink_purchase_bill(uuid,bigint);
drop function if exists public.quo_get_catering_supplies(uuid);
drop function if exists public.quo_search_catering_supply_sources(uuid,text,integer);
drop function if exists public.quo_allocate_structured_supply(uuid,bigint,numeric,text);
drop function if exists public.quo_allocate_manual_supply(uuid,bigint,text,numeric,text,numeric,text);
drop function if exists public.quo_remove_catering_supply(bigint);
drop function if exists public.quo_bill_catering_usage(bigint);
drop table if exists public.quo_catering_supply_allocations;
drop table if exists public.quo_purchase_bill_links;

create table if not exists public.quo_supply_usage (
  id bigint generated by default as identity primary key,
  document_id uuid not null references public.quo_documents(id) on delete cascade,
  supply_name text not null,
  quantity numeric(14,4) not null check (quantity > 0),
  unit text not null default 'PCS' check (unit in ('KG','G','PCS','L','ML','CSE')),
  used_on date not null default current_date,
  note text,
  created_by uuid not null references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists quo_supply_usage_document_idx
  on public.quo_supply_usage(document_id, used_on desc, id desc);
create index if not exists quo_supply_usage_name_idx
  on public.quo_supply_usage(lower(supply_name));

alter table public.quo_supply_usage enable row level security;

drop policy if exists quo_supply_usage_admin_select on public.quo_supply_usage;
create policy quo_supply_usage_admin_select
on public.quo_supply_usage
for select to authenticated
using (public.quo_is_admin());

revoke all on public.quo_supply_usage from anon;
revoke insert, update, delete on public.quo_supply_usage from authenticated;
grant select on public.quo_supply_usage to authenticated;

create or replace function public.quo_supply_usage_list(
  p_search text default null,
  p_document_id uuid default null,
  p_limit integer default 500
)
returns table(
  usage_id bigint,
  document_id uuid,
  document_number text,
  document_type text,
  document_status text,
  customer_name text,
  event_name text,
  service_from date,
  service_to date,
  supply_name text,
  quantity numeric,
  unit text,
  used_on date,
  note text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_search text:=lower(btrim(coalesce(p_search,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,500),1000));
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  return query
  select
    u.id,
    d.id,
    d.document_number,
    d.document_type,
    d.status,
    d.customer_name,
    d.event_name,
    d.service_from,
    d.service_to,
    u.supply_name,
    u.quantity,
    u.unit,
    u.used_on,
    u.note,
    u.created_at
  from public.quo_supply_usage u
  join public.quo_documents d on d.id=u.document_id
  where d.deleted_at is null
    and (p_document_id is null or u.document_id=p_document_id)
    and (
      v_search=''
      or lower(coalesce(u.supply_name,'')) like '%'||v_search||'%'
      or lower(coalesce(d.document_number,'')) like '%'||v_search||'%'
      or lower(coalesce(d.customer_name,'')) like '%'||v_search||'%'
      or lower(coalesce(d.event_name,'')) like '%'||v_search||'%'
      or lower(coalesce(u.note,'')) like '%'||v_search||'%'
    )
  order by u.used_on desc,u.id desc
  limit v_limit;
end;
$func$;

create or replace function public.quo_add_supply_usage(
  p_document_id uuid,
  p_supply_name text,
  p_quantity numeric,
  p_unit text,
  p_used_on date default current_date,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_id bigint;
  v_unit text:=upper(btrim(coalesce(p_unit,'PCS')));
  v_name text:=btrim(coalesce(p_supply_name,''));
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  if v_name='' then raise exception 'Enter the supply name'; end if;
  if coalesce(p_quantity,0)<=0 then raise exception 'Quantity must be greater than zero'; end if;
  if v_unit not in ('KG','G','PCS','L','ML','CSE') then raise exception 'Invalid unit'; end if;

  if not exists(
    select 1 from public.quo_documents d
    where d.id=p_document_id
      and d.deleted_at is null
      and d.document_type in ('quotation','invoice')
  ) then raise exception 'Select an existing quotation or invoice'; end if;

  insert into public.quo_supply_usage(document_id,supply_name,quantity,unit,used_on,note,created_by)
  values(
    p_document_id,
    v_name,
    round(p_quantity,4),
    v_unit,
    coalesce(p_used_on,current_date),
    nullif(btrim(coalesce(p_note,'')),''),
    auth.uid()
  )
  returning id into v_id;

  return v_id;
end;
$func$;

create or replace function public.quo_remove_supply_usage(p_usage_id bigint)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;
  delete from public.quo_supply_usage where id=p_usage_id;
end;
$func$;

revoke all on function public.quo_supply_usage_list(text,uuid,integer) from public,anon;
revoke all on function public.quo_add_supply_usage(uuid,text,numeric,text,date,text) from public,anon;
revoke all on function public.quo_remove_supply_usage(bigint) from public,anon;
grant execute on function public.quo_supply_usage_list(text,uuid,integer) to authenticated;
grant execute on function public.quo_add_supply_usage(uuid,text,numeric,text,date,text) to authenticated;
grant execute on function public.quo_remove_supply_usage(bigint) to authenticated;
