-- Quo v71: Admin-only purchase bill links for confirmed customer quotations.
-- A Quo quotation is a customer sale document. Bills are linked as supply costs,
-- not treated as supplier quotations. Existing Quo and Bills records are unchanged.

create table if not exists public.quo_purchase_bill_links (
  id bigint generated by default as identity primary key,
  quotation_id uuid not null references public.quo_documents(id) on delete cascade,
  bill_id bigint not null references public.bills(id) on delete restrict,
  linked_by uuid not null references auth.users(id) on delete restrict,
  linked_at timestamptz not null default now(),
  note text,
  unique (quotation_id, bill_id)
);

create index if not exists quo_purchase_bill_links_quotation_idx
  on public.quo_purchase_bill_links(quotation_id, linked_at desc);
create index if not exists quo_purchase_bill_links_bill_idx
  on public.quo_purchase_bill_links(bill_id);

alter table public.quo_purchase_bill_links enable row level security;

drop policy if exists quo_purchase_bill_links_admin_select on public.quo_purchase_bill_links;
create policy quo_purchase_bill_links_admin_select
on public.quo_purchase_bill_links
for select to authenticated
using (public.quo_is_admin());

revoke all on public.quo_purchase_bill_links from anon;
revoke insert, update, delete on public.quo_purchase_bill_links from authenticated;
grant select on public.quo_purchase_bill_links to authenticated;

create or replace function public.quo_get_purchase_bill_links(p_quotation_id uuid)
returns table(
  link_id bigint,
  bill_id bigint,
  bill_no text,
  bill_day date,
  vendor text,
  amount numeric,
  payment_status text,
  approval_status text,
  linked_at timestamptz
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  if not exists(
    select 1 from public.quo_documents q
    where q.id=p_quotation_id
      and q.document_type='quotation'
      and q.deleted_at is null
  ) then raise exception 'Quotation not found'; end if;

  return query
  select
    l.id,
    b.id,
    coalesce(nullif(b.bill_no,''),nullif(b."Bill No",''),'#'||b.id::text),
    coalesce(
      b.bill_day,
      case when coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''),'') ~ '^\d{4}-\d{2}-\d{2}$'
        then coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''))::date
        else null end
    ),
    coalesce(nullif(b.vendor,''),nullif(b."Vendor",''),'Unknown supplier'),
    coalesce(
      b.net_amount,
      nullif(regexp_replace(coalesce(nullif(b.amount,''),nullif(b."Amount",''),''),'[^0-9.-]','','g'),'')::numeric,
      0::numeric
    ),
    coalesce(nullif(b.payment_status,''),'Pending'),
    coalesce(nullif(b.approval_status,''),'Recorded'),
    l.linked_at
  from public.quo_purchase_bill_links l
  join public.bills b on b.id=l.bill_id
  where l.quotation_id=p_quotation_id
    and b.deleted_at is null
  order by coalesce(b.bill_day,b.created_at::date) desc,b.id desc;
end;
$func$;

create or replace function public.quo_purchase_bill_candidates(
  p_quotation_id uuid,
  p_search text default null,
  p_limit integer default 100
)
returns table(
  bill_id bigint,
  bill_no text,
  bill_day date,
  vendor text,
  amount numeric,
  payment_status text,
  approval_status text
)
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_search text:=lower(btrim(coalesce(p_search,'')));
  v_limit integer:=greatest(1,least(coalesce(p_limit,100),200));
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  if not exists(
    select 1 from public.quo_documents q
    where q.id=p_quotation_id
      and q.document_type='quotation'
      and q.deleted_at is null
      and q.status in ('Confirmed','Accepted')
  ) then raise exception 'Purchase bills can be linked only to a confirmed quotation'; end if;

  return query
  select
    b.id,
    coalesce(nullif(b.bill_no,''),nullif(b."Bill No",''),'#'||b.id::text),
    coalesce(
      b.bill_day,
      case when coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''),'') ~ '^\d{4}-\d{2}-\d{2}$'
        then coalesce(nullif(b.bill_date,''),nullif(b."Bill Date",''))::date
        else null end
    ),
    coalesce(nullif(b.vendor,''),nullif(b."Vendor",''),'Unknown supplier'),
    coalesce(
      b.net_amount,
      nullif(regexp_replace(coalesce(nullif(b.amount,''),nullif(b."Amount",''),''),'[^0-9.-]','','g'),'')::numeric,
      0::numeric
    ),
    coalesce(nullif(b.payment_status,''),'Pending'),
    coalesce(nullif(b.approval_status,''),'Recorded')
  from public.bills b
  where b.deleted_at is null
    and not exists(
      select 1 from public.quo_purchase_bill_links l
      where l.quotation_id=p_quotation_id and l.bill_id=b.id
    )
    and (
      v_search=''
      or lower(coalesce(b.bill_no,b."Bill No",'')) like '%'||v_search||'%'
      or lower(coalesce(b.vendor,b."Vendor",'')) like '%'||v_search||'%'
      or lower(coalesce(b.location,b."Location",'')) like '%'||v_search||'%'
    )
  order by coalesce(b.bill_day,b.created_at::date) desc,b.id desc
  limit v_limit;
end;
$func$;

create or replace function public.quo_link_purchase_bill(
  p_quotation_id uuid,
  p_bill_id bigint,
  p_note text default null
)
returns bigint
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
declare
  v_id bigint;
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  if not exists(
    select 1 from public.quo_documents q
    where q.id=p_quotation_id
      and q.document_type='quotation'
      and q.deleted_at is null
      and q.status in ('Confirmed','Accepted')
  ) then raise exception 'Purchase bills can be linked only to a confirmed quotation'; end if;

  if not exists(select 1 from public.bills b where b.id=p_bill_id and b.deleted_at is null)
    then raise exception 'Purchase bill not found'; end if;

  insert into public.quo_purchase_bill_links(quotation_id,bill_id,linked_by,note)
  values(p_quotation_id,p_bill_id,auth.uid(),nullif(btrim(coalesce(p_note,'')),''))
  on conflict (quotation_id,bill_id)
  do update set linked_by=excluded.linked_by,linked_at=now(),note=coalesce(excluded.note,public.quo_purchase_bill_links.note)
  returning id into v_id;

  return v_id;
end;
$func$;

create or replace function public.quo_unlink_purchase_bill(
  p_quotation_id uuid,
  p_bill_id bigint
)
returns void
language plpgsql
security definer
set search_path=public,pg_temp
as $func$
begin
  if auth.uid() is null then raise exception 'Authentication required'; end if;
  if not public.quo_is_admin() then raise exception 'Administrator access required'; end if;

  delete from public.quo_purchase_bill_links
  where quotation_id=p_quotation_id and bill_id=p_bill_id;
end;
$func$;

revoke all on function public.quo_get_purchase_bill_links(uuid) from public,anon;
revoke all on function public.quo_purchase_bill_candidates(uuid,text,integer) from public,anon;
revoke all on function public.quo_link_purchase_bill(uuid,bigint,text) from public,anon;
revoke all on function public.quo_unlink_purchase_bill(uuid,bigint) from public,anon;

grant execute on function public.quo_get_purchase_bill_links(uuid) to authenticated;
grant execute on function public.quo_purchase_bill_candidates(uuid,text,integer) to authenticated;
grant execute on function public.quo_link_purchase_bill(uuid,bigint,text) to authenticated;
grant execute on function public.quo_unlink_purchase_bill(uuid,bigint) to authenticated;
